name: yahay
description: "A new Flutter Chat Application. Uses Laravel + Php as backend"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  rxdart: ^0.27.7
  get_it: ^7.7.0
  dio: ^5.4.3+1
  mockito: ^5.4.4
  collection: ^1.18.0
  intl: ^0.19.0
  dart_pusher_channels: ^1.1.1
  cached_network_image: ^3.3.1
  flutter_blurhash: ^0.8.2
  auto_route: ^8.1.3
  permission_handler: ^11.3.1
  gal: ^2.3.0
  image_picker: ^1.1.1
  flex_color_scheme: ^7.3.1
  shared_preferences: ^2.2.3
  timeago: ^3.6.1
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  fluttertoast: ^8.2.5
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  rename: ^3.0.2
  firebase_core: ^2.30.1
  firebase_crashlytics: ^3.5.5
  talker: ^4.2.0
  uuid: ^4.4.0
  emoji_picker_flutter: ^2.2.0

  # for video streaming
  flutter_webrtc: ^0.11.1
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  auto_route_generator: ^8.0.0
  package_info_plus: any
  wakelock_windows: any
  win32: any
  build_runner: ^2.4.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/default_images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#    - family: BriemHand
#      fonts:
#        - asset: assets/fonts/BriemHand/BriemHand-Regular.ttf
#        - asset: assets/fonts/BriemHand/BriemHand-Medium.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
