# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
<<<<<<< HEAD
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" , "dev" ]
=======
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
>>>>>>> e718688 (Create dart.yml)

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
<<<<<<< HEAD
          flutter-version: 3.22.1
=======
          flutter-version: "3.3.4"
>>>>>>> e718688 (Create dart.yml)
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
<<<<<<< HEAD
          channel: stable
=======
          flutter-version: "3.3.4"
>>>>>>> e718688 (Create dart.yml)
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build ios --release --no-codesign
